[project]
name = "game-maze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dearpygui>=2.1.1",
    "nicegui>=3.4.1",
]
